const path = require("path");
//const TerserPlugin = require('terser-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: {
    "hello-world": "./src/hello-world.js",
    "kiwi": "./src/kiwi.js",
  },
  output: {
    filename: "[name].[contenthash].js",
    path: path.resolve(__dirname, "./dist"),
    // Without this property webpack doesnt know where for static assests for example.
    publicPath: "/static/"
  },
  mode: "production",
  // This will extract lodash, react etc... dependencies that we have in this project from `hello-world.js` and `kiwi.js` to its own file
  // that can be cached by the browser regardless any changes that we do in other files.
  optimization: {
    splitChunks: {
      chunks: "all",
      // By default is 30kb, so if we want react to be in seperated chunk/bundle
      // we need to lower the threshhold.
      minSize: 10000,
      automaticNameDelimiter: "_"
    }
  },
  module: {
    rules: [
      {
        test: /\.(png|jpg)$/,
        use: [
          // By default the file name in the output bundle will
          // be its md5 value + the original exention
          "file-loader"
        ]
      },
      {
        test: /\.css$/,
        // Extracts CSS into separate files.
        // take all css/scss files and put them in a single flle - styles.css.
        use: [MiniCssExtractPlugin.loader, "css-loader"]
      },
      {
        test: /\.scss$/,
        // webpack will process from right to left
        // starting with the `sass-loader` converting everything to regular css.
        use: [MiniCssExtractPlugin.loader, "css-loader", "sass-loader"]
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["@babel/env"],
            plugins: ["transform-class-properties"]
          }
        }
      },
      {
        test: /\.hbs$/,
        use: ["handlebars-loader"]
      }
    ]
  },
  plugins: [
    // This plugin is included in production by default.
    //new TerserPlugin(),
    new MiniCssExtractPlugin({
      filename: "[name].[contenthash].css"
    }),
    new CleanWebpackPlugin({
      cleanOnceBeforeBuildPatterns: [
        "**/*", // relative to the `dist` folder
        path.join(process.cwd(), "build/**/*") // absolute path for anything outside the `dist` folder.
      ]
    }),
    new HtmlWebpackPlugin({
      title: "Hello World",
      filename: "hello-world.html",
      template: "src/template.hbs",
      // `hello-world` is the name from the property naes in the `entry` block.
      // `vendors_hello-world_kiwi` is the lodash bundle generated by the `optimization` block.
      // `vendors_hello-world` is bootstrap.js that being used only in `hello-world.html`
      chunks: ["hello-world", "vendors_hello-world_kiwi", "vendors_hello-world"],
      meta: {
        viewport: "width=device-width, initial-scale=1",
        description: "Hello World Description"
      }
    }),
    new HtmlWebpackPlugin({
      title: "Kiwi",
      filename: "kiwi.html",
      chunks: ["kiwi", "vendors_hello-world_kiwi"],
      template: "src/template.hbs",
      meta: {
        viewport: "width=device-width, initial-scale=1",
        description: "Kiwi Description"
      }
    })
  ]
};
